### ISSUE TITLE
Error when reanalysing (overwriting) movie with different settings (master branch)

### ISSUE THREAD

**Issue by sylviaschroeder** [mkrumin/EyeTracking#10]
Undefined function or variable 'fps'.

Error in runAnalysis (line 60)
            i-1, length(h.framesToAnalyze), fps, ...

Error in etGUI>RunToggle_Callback (line 267)
handles = runAnalysis(hObject, eventdata, handles);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in etGUI (line 42)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)etGUI('RunToggle_Callback',hObject,eventdata,guidata(hObject))
Error while evaluating UIControl Callback

**Comment by mkrumin** [comment]
Was it a small number of frames? probably less than a hundred?
