### ISSUE TITLE
Error when plotting results on dataset that caused error before (see issue #10; master branch)

### ISSUE THREAD

**Issue by sylviaschroeder** [mkrumin/EyeTracking#11]
Error using ylim (line 31)
Limits must be a 2-element vector of increasing numeric values.

Error in plotTraces (line 60)
    ylim([min(h.results.x(nonBlinkIdx)),
    max(h.results.x(nonBlinkIdx))]);

Error in etGUI>PlotPush_Callback (line 330)
handles = plotTraces(hObject, eventdata, handles);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in etGUI (line 42)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)etGUI('PlotPush_Callback',hObject,eventdata,guidata(hObject))
Error while evaluating UIControl Callback

**Comment by mkrumin** [comment]
Should be fixed now
