### ISSUE TITLE
Suggestion: do not rescale ylimits when plotting results again (master branch)

### ISSUE THREAD

**Issue by sylviaschroeder** [mkrumin/EyeTracking#12]
Often the ylimits of results are far too large because of some outliers. Once one has set the ylimits to a good value, this should not change when plotting the results again.
Alternatively, one could ignore all values during blinks for example when setting the ylimits.

**Comment by mkrumin** [comment]
The values during blinks are ignored already.  
The problem with ymin([minValue maxValue]) is that in some cases it will not allow you to interactively zoom out beyond these values.
