### ISSUE TITLE
Suggestion: plot blink data in different colour

### ISSUE THREAD

**Issue by sylviaschroeder** [mkrumin/EyeTracking#17]
It is often hard to see when blinks are starting and ending in the plot of the pupil area (same for x and y position) It would be good if one could easily see the area values outside of blink episodes to detect when things go wrong around the blinks. So, instead of plotting red dots, one could plot data in blink episodes in a different colour, and even better: there could be a button and when clicked, only "good" data (outside of blink episodes is plotted, so that bad values stand out immediately.

**Comment by mkrumin** [comment]
Ctrl+B will now toggle blinks data on/off (When the results figure is in focus and no tool is selected). Plotting is also done differently now.
