### ISSUE TITLE
Separate analysis of blinks and pupil

### ISSUE THREAD

**Issue by sylviaschroeder** [mkrumin/EyeTracking#21]
There should be an option of analysing blinks without changing the pupil data

**Comment by mkrumin** [comment]
I am not sure how this should work exactly. What currently happens is that every frame has its blinkRho value estimated within the Blink ROI that was in place when that frame was analyzed. Then, blinkRho is thresholded by the value in the box to the left of the Blink ROI button. This is done globally, all the frames have the same blink detection threshold, and when you change the threshold it is applied to all the frames. This is probably too inflexible. So:  
- what frames to blink-analyze? do we need single frame blink detection?  
- does the threshold need to be global or every frame can have its threshold?

**Comment by sylviaschroeder** [comment]
I think the global threshold is fine. I can't imagine to try and change the threshold for single frames.
What I meant is: if I want to reanalyse the blink detection (by changing the ROI), I don't to reanalyse the pupil measurements as well. These two things should be separated like in the previous etGUI. At least, there should be an option to keep the pupil data as is.

**Comment by mkrumin** [comment]
In the previous gui there was no option to analyze them together, which was wasting a lot of time, as reading the frames from disk to memory is expensive. And this was wrong  
I guess a separate button to analyze blinks only will do. That way you have the option to either analyze all, or analyze blinks only. There might be the third option to only analyze pupil, but I want to keep the number of options to minimum, makes it a more stable gui.

**Comment by sylviaschroeder** [comment]
Deal

**Comment by mkrumin** [comment]
Done, [commit 49665fc](https://github.com/mkrumin/EyeTracking/commit/49665fc75a592668a2e1a44e509f36c2b77be3b1)
