### ISSUE TITLE
blink detection

### ISSUE THREAD

**Issue by eakjacobs** [mkrumin/EyeTracking#23]
I'm not sure how straight forward this would be to implement, but I have a problem in a few datasets in which the eye of the mouse is almost closed during a large amount of frames (sometime half or more). Because the blink detection just uses the average of all frames across the movie, it doesn't correctly pick up the frames during which the mouse is effectively/almost blinking. There are parts in the movie where the whole eye is visible though and I'd like to be able to use at least those segments for pupil analysis. Rather than using the average, it would be very helpful if I could specify which frames to use for calculating the correlation - so I can essentially tell the algorithm 'this is what an open, non-blinking eye looks like. use this as your reference'.
Thanks!

**Comment by mkrumin** [comment]
Now blink detection in done in a two-dimensional space - correlation coefficient and mean brightness of the frame inside the Blink ROI. You can draw a polygon in this space (click on Blink Classifier and edit the polygon in the results figure) to define what you want to be detected as blinks. This should help with half-closed eye issue.
